### ISSUE TITLE
Potential mod compatibility issues?

### ISSUE THREAD

**Issue by Ariannae** [unascribed/aether-unofficial-issues#3]
Gunna toss in a few potential compatibility issues. Confirmation on them would be awesome, if at all possible.
The first one looks as though it has something to do with music, which I assume was changed around in 1.5.2, as there happened to be new music playing when I went through the portal. I have a mod called Music Choices configured to play music on the main menu screen, and had to get rid of that part to get the game to load up. This happened as the main menu was loading up. [Pastebin link to crash portion.] (http://pastebin.com/tHzp9kWV)
I know it indicates Music Choices, but this had not happened in version 1.5.1, so I assume it has to do with how they're attempting to implement music and probably hooking into the main menu. I can supply the full forge log as well if requested, but it's a rather large file.

The second issue I'm having some trouble figuring out, however. Basically, it looks as though something with Smart Moving/RenderPlayer API and Aether is not working properly together, but it looks like it's restricted to my mod pack, as I was unable to reproduce it with -only- those two mods loaded (Which means it could be a third mod interfering?). While playing in first person mode, the game runs entirely fine and is more than playable. However, upon switching to third person mode, the gameRenderer eats up more and more resources until it inevitably stalls out or crashes. However, switching back to first person alleviates the problem until switching back into third person. I have a stall log that comes from FastCraft's Sampler add-on. [Link to that] (http://pastebin.com/10wv2Jey). I know that it's indicating RenderPlayer API in this, but it only occurs when Aether is present for some reason. I'm not sure if I should report it to the author of RenderPlayer API as well, or if Aether is improperly hooking into something, or if it is simply incompatible. I apologize for not being of much use in this particular instance, but I'd love some input on what it could possibly be.

**Comment by unascribed** [comment]
If it would be feasible, could you debug your modpack to find what the third mod causing the second issue is? That'd help a lot to pinpointing the issue. I generally consider interactions with my mods between OptiFine, SmartMoving, AnimatedPlayers, etc to not have support, due to how deeply these mods hook the code, but if the issue is simple enough I could fix it.

For the first issue, people appear to have the issue with base Aether II as well. It seems to be the Aether music doesn't have a positioned sound record, as it's music without a position, and MusicChoices is blindly trying to find a positioned sound record. The best place to fix this would be in MusicChoices, not Aether. Since it's open source, I'll make a PR and supply a pre-built version with the patch.

**Comment by Ariannae** [comment]
Upon further debugging, it looks like I was in error when I said that I couldn't reproduce it with just the two mods. With a clean Minecraft install and Forge 1566, Smart Moving and its prerequisites and Unofficial Aether, I was able to reproduce it. It just takes longer, more than likely due to less memory usage. Simply standing in one location while in third person view with Smart Moving will end up lagging the server out in the same manner as my mod pack. I'll have to lower the Forge versions and try with the previous Aether update as well.

The issue with music makes sense. Wasn't sure whether to notify you guys here or not, simply because the previous version hadn't had the issue for some reason. But thank you for the clarification!

**Comment by Ariannae** [comment]
Music Choice's compatibility issue doesn't appear in the most recent release (Of which I had downloaded, but hadn't updated to), and so was completely on my end. I apologize!

**Comment by BBoldt** [comment]
too late, you're fired!
